/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.*; 
import model.User;

/**
 *
 * @author USER
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    
    private User currentUser;
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(User user) {
    this.currentUser = user;
    initComponents();
    setResizable(false);
    setLocationRelativeTo(null);
    setTitle("Admin Dashboard - Welcome " + user.getUsername());
    setLocationRelativeTo(null); // center the window
}

    
     private void handleSelection() {
        String selected = (String) comboActions.getSelectedItem();

        switch (selected) {
            case "Register User":
                RegisterUserForm registerUserForm = new RegisterUserForm();
                registerUserForm.setVisible(true);
                dispose();
                break;
            case "View Users":
                ViewUsersForm usersForm= new ViewUsersForm();
                usersForm.setVisible(true);
                dispose();
                break;
            case "Update User":
                User user= new User();
                UpdateUserForm userForm= new UpdateUserForm(user);
                userForm.setVisible(true);
                dispose();
                break;
            case "Delete User":
                DeleteUserForm deleteUserForm= new DeleteUserForm();
                deleteUserForm.setVisible(true);
                dispose();
                break;
            case "Register Product":                
                dispose();
                break;
            case "Update Product Status":
                new ProductStatusForm(currentUser).setVisible(true);
                dispose();
                break;     
            case "Logout":
                new LoginForm().setVisible(true);
                dispose();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select a valid action.", "Invalid Choice", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblChoose = new javax.swing.JLabel();
        comboActions = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lblChoose.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblChoose.setForeground(new java.awt.Color(255, 255, 255));
        lblChoose.setText("Choose Action");

        comboActions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Action", "Register User", "View Users", "Update User", "Delete User", "Register Product", "Update Product Status", "Logout" }));
        comboActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Dashboard");

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblChoose)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboActions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblChoose)
                    .addComponent(comboActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btnGo)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionsActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        handleSelection();
    }//GEN-LAST:event_btnGoActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JComboBox<String> comboActions;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChoose;
    // End of variables declaration//GEN-END:variables
}
