/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.*; 
import model.User;
import java.awt.GridLayout;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Dimension;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author USER
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    
    private User currentUser;
    private JButton btnRegisterUser;
    private JButton btnViewUsers;
    private JButton btnUpdateUser;
    private JButton btnDeleteUser;
    private JButton btnRegisterProduct;
    private JButton btnUpdateProductStatus;
    private JButton btnViewProductDetails; // New button declaration
    private JButton btnLogout;
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(User user) {
    this.currentUser = user;
    initComponents();
    setResizable(false);
    setLocationRelativeTo(null);
    setTitle("Admin Dashboard - Welcome " + user.getUsername());
    setLocationRelativeTo(null); // center the window
}

    
     private void handleSelection(String actionCommand) {
        switch (actionCommand) {
            case "Register User":
                RegisterUserForm registerUserForm = new RegisterUserForm();
                registerUserForm.setVisible(true);
                dispose();
                break;
            case "View Users":
                ViewUsersForm usersForm= new ViewUsersForm();
                usersForm.setVisible(true);
                dispose();
                break;
            case "Update User":
                User userToUpdate = new User(); // Assuming a default or selection mechanism later
                UpdateUserForm updateUserForm = new UpdateUserForm(userToUpdate);
                updateUserForm.setVisible(true);
                dispose();
                break;
            case "Delete User":
                DeleteUserForm deleteUserForm= new DeleteUserForm();
                deleteUserForm.setVisible(true);
                dispose();
                break;
            case "Register Product":
                // Assuming RegisterProductForm exists and needs the current user
                RegisterProductForm registerProductForm = new RegisterProductForm(currentUser);
                registerProductForm.setVisible(true);
                dispose();
                break;
            case "Update Product Status":
                new ProductStatusForm(currentUser).setVisible(true);
                dispose();
                break;
            case "View Product Details":
                new ViewProductDetailsForm(currentUser).setVisible(true);
                dispose();
                break;
            case "Logout":
                new LoginForm().setVisible(true);
                dispose();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select a valid action.", "Invalid Choice", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel mainPanel = new JPanel(new BorderLayout(10, 10)); // Added BorderLayout
        mainPanel.setBorder(new EmptyBorder(20, 20, 20, 20)); // Added padding
        mainPanel.setBackground(new java.awt.Color(102, 102, 102));


        JLabel titleLabel = new JLabel("Admin Control Panel", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Tahoma", Font.BOLD, 20)); // Consistent font
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(titleLabel, BorderLayout.NORTH);

        JPanel buttonPanel = new JPanel(new GridLayout(8, 1, 10, 10)); // Adjusted GridLayout to 8 rows
        buttonPanel.setBackground(new java.awt.Color(102, 102, 102)); // Match background

        Font buttonFont = new Font("Tahoma", Font.PLAIN, 14); // Consistent font for buttons
        Dimension buttonSize = new Dimension(200, 40); // Consistent button size

        btnRegisterUser = new JButton("Register User");
        btnRegisterUser.setFont(buttonFont);
        btnRegisterUser.setPreferredSize(buttonSize);
        btnRegisterUser.addActionListener(evt -> handleSelection("Register User"));
        buttonPanel.add(btnRegisterUser);

        btnViewUsers = new JButton("View Users");
        btnViewUsers.setFont(buttonFont);
        btnViewUsers.setPreferredSize(buttonSize);
        btnViewUsers.addActionListener(evt -> handleSelection("View Users"));
        buttonPanel.add(btnViewUsers);

        btnUpdateUser = new JButton("Update User");
        btnUpdateUser.setFont(buttonFont);
        btnUpdateUser.setPreferredSize(buttonSize);
        btnUpdateUser.addActionListener(evt -> handleSelection("Update User"));
        buttonPanel.add(btnUpdateUser);

        btnDeleteUser = new JButton("Delete User");
        btnDeleteUser.setFont(buttonFont);
        btnDeleteUser.setPreferredSize(buttonSize);
        btnDeleteUser.addActionListener(evt -> handleSelection("Delete User"));
        buttonPanel.add(btnDeleteUser);

        btnRegisterProduct = new JButton("Register Product");
        btnRegisterProduct.setFont(buttonFont);
        btnRegisterProduct.setPreferredSize(buttonSize);
        btnRegisterProduct.addActionListener(evt -> handleSelection("Register Product"));
        buttonPanel.add(btnRegisterProduct);

        btnUpdateProductStatus = new JButton("Update Product Status");
        btnUpdateProductStatus.setFont(buttonFont);
        btnUpdateProductStatus.setPreferredSize(buttonSize);
        btnUpdateProductStatus.addActionListener(evt -> handleSelection("Update Product Status"));
        buttonPanel.add(btnUpdateProductStatus);

        btnViewProductDetails = new JButton("View Product Details");
        btnViewProductDetails.setFont(buttonFont);
        btnViewProductDetails.setPreferredSize(buttonSize);
        btnViewProductDetails.setToolTipText("Search for products and view their details and status history.");
        btnViewProductDetails.addActionListener(evt -> handleSelection("View Product Details"));
        buttonPanel.add(btnViewProductDetails);

        btnLogout = new JButton("Logout");
        btnLogout.setFont(buttonFont);
        btnLogout.setPreferredSize(buttonSize);
        btnLogout.addActionListener(evt -> handleSelection("Logout"));
        buttonPanel.add(btnLogout);

        mainPanel.add(buttonPanel, BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(mainPanel); // Add mainPanel to frame
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Removed comboActions, btnGo, jLabel2, lblChoose
    // Removed comboActions, btnGo, jLabel2, lblChoose
    // jPanel1 is replaced by mainPanel and buttonPanel
    // End of variables declaration//GEN-END:variables
}
